<?php

$y=0;
$apps[$x]['menu'][$y]['title']['en-us'] = 'Messages';
$apps[$x]['menu'][$y]['title']['en-gb'] = 'Messages';
$apps[$x]['menu'][$y]['title']['ar-eg'] = 'رسائل';
$apps[$x]['menu'][$y]['title']['de-at'] = 'Mitteilungen';
$apps[$x]['menu'][$y]['title']['de-ch'] = 'Mitteilungen';
$apps[$x]['menu'][$y]['title']['de-de'] = 'Mitteilungen';
$apps[$x]['menu'][$y]['title']['es-cl'] = 'Mensajes';
$apps[$x]['menu'][$y]['title']['es-mx'] = 'Mensajes';
$apps[$x]['menu'][$y]['title']['fr-ca'] = 'messages';
$apps[$x]['menu'][$y]['title']['fr-fr'] = 'messages';
$apps[$x]['menu'][$y]['title']['he-il'] = 'הודעות';
$apps[$x]['menu'][$y]['title']['it-it'] = 'Messaggi';
$apps[$x]['menu'][$y]['title']['nl-nl'] = 'Berichten';
$apps[$x]['menu'][$y]['title']['pl-pl'] = 'Wiadomości';
$apps[$x]['menu'][$y]['title']['pt-br'] = 'Mensagens';
$apps[$x]['menu'][$y]['title']['pt-pt'] = 'Mensagens';
$apps[$x]['menu'][$y]['title']['ro-ro'] = 'Mesaje';
$apps[$x]['menu'][$y]['title']['ru-ru'] = 'Сообщения';
$apps[$x]['menu'][$y]['title']['uk-ua'] = 'Повідомлення';
$apps[$x]['menu'][$y]['title']['sv-se'] = 'Meddelanden';
$apps[$x]['menu'][$y]['title']['zh-cn'] = '留言';
$apps[$x]['menu'][$y]['title']['ja-jp'] = 'メッセージ';
$apps[$x]['menu'][$y]['title']['ko-kr'] = '메시지';
$apps[$x]['menu'][$y]['uuid'] = 'b2f6a2e0-cf25-4bd5-8079-6385f6871047';
$apps[$x]['menu'][$y]['parent_uuid'] = 'fd29e39c-c936-f5fc-8e2b-611681b266b5';
$apps[$x]['menu'][$y]['category'] = 'internal';
$apps[$x]['menu'][$y]['path'] = '/app/messages/messages.php';
$apps[$x]['menu'][$y]['groups'][] = 'superadmin';
$y++;
$apps[$x]['menu'][$y]['title']['en-us'] = 'Message Summary';
$apps[$x]['menu'][$y]['title']['en-gb'] = 'Message Summary'; 
$apps[$x]['menu'][$y]['title']['ar-eg'] = 'ملخص الرسائل'; 
$apps[$x]['menu'][$y]['title']['de-at'] = 'Nachrichtenübersicht'; 
$apps[$x]['menu'][$y]['title']['de-ch'] = 'Nachrichtenübersicht'; 
$apps[$x]['menu'][$y]['title']['de-de'] = 'Nachrichtenübersicht'; 
$apps[$x]['menu'][$y]['title']['es-cl'] = 'Resumen de Mensajes'; 
$apps[$x]['menu'][$y]['title']['es-mx'] = 'Resumen de Mensajes'; 
$apps[$x]['menu'][$y]['title']['fr-ca'] = 'Résumé des messages'; 
$apps[$x]['menu'][$y]['title']['fr-fr'] = 'Résumé des messages'; 
$apps[$x]['menu'][$y]['title']['he-il'] = 'סיכום הודעות'; 
$apps[$x]['menu'][$y]['title']['it-it'] = 'Riepilogo Messaggi'; 
$apps[$x]['menu'][$y]['title']['nl-nl'] = 'Berichten Samenvatting'; 
$apps[$x]['menu'][$y]['title']['pl-pl'] = 'Podsumowanie Wiadomości'; 
$apps[$x]['menu'][$y]['title']['pt-br'] = 'Resumo das Mensagens'; 
$apps[$x]['menu'][$y]['title']['pt-pt'] = 'Resumo das Mensagens'; 
$apps[$x]['menu'][$y]['title']['ro-ro'] = 'Sumar Mesaje'; 
$apps[$x]['menu'][$y]['title']['ru-ru'] = 'Сводка сообщений'; 
$apps[$x]['menu'][$y]['title']['uk-ua'] = 'Резюме повідомлень'; 
$apps[$x]['menu'][$y]['title']['sv-se'] = 'Sammanfattning av meddelanden'; 
$apps[$x]['menu'][$y]['title']['zh-cn'] = '消息摘要'; 
$apps[$x]['menu'][$y]['title']['ja-jp'] = 'メッセージ概要'; 
$apps[$x]['menu'][$y]['title']['ko-kr'] = '메시지 요약'; 
$apps[$x]['menu'][$y]['uuid'] = '01d05576-739c-495f-84bb-662c5f755120';
$apps[$x]['menu'][$y]['parent_uuid'] = '0438b504-8613-7887-c420-c837ffb20cb1';
$apps[$x]['menu'][$y]['category'] = 'internal';
$apps[$x]['menu'][$y]['path'] = '/app/messages/message_summary.php';
$apps[$x]['menu'][$y]['groups'][] = 'superadmin';
$apps[$x]['menu'][$y]['groups'][] = 'admin';
$y++;

?>